on:
  push:
    branches:
      - feature/autorelease-dev

permissions:
  contents: write
  pull-requests: write

name: release

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      #- uses: actions/create-github-app-token@v1
      #  id: app-token
      #  with:
      #    app-id: ${{ secrets.APP_ID_RELEASE }}
      #    private-key: ${{ secrets.APP_PKEY_RELEASE }}
      #    owner: ${{ github.repository_owner }}
      #    repositories: "release-please-pnpm-mororepo-poc"

      - uses: actions/checkout@v4
      - run: echo "Hello, World! ${{ github.ref }}"
        shell: bash
      - run: |
          env | grep GITHUB_REF

      #- uses: codaxio/cdx@v0.14.0
      #  with:
      #    #token: ${{ steps.app-token.outputs.token }}
      #    token: hello
      #    config-file: cli.config.ts