on:
  pull_request:
    types: 
      - opened
      - closed
      - synchronize
    branches:
      - release/dev
  #    - feature/autorelease-dev
 
  #workflow_dispatch:
  #  inputs:
  #    ref:
  #      description: 'Ref'
  #      required: true


permissions:
  contents: write
  pull-requests: write

name: release

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo The PR was merged
  release:
    env:
      GH_TOKEN: ${{ github.token }}
    runs-on: ubuntu-latest
    steps:
      #- uses: actions/create-github-app-token@v1
      #  id: app-token
      #  with:
      #    app-id: ${{ secrets.APP_ID_RELEASE }}
      #    private-key: ${{ secrets.APP_PKEY_RELEASE }}
      #    owner: ${{ github.repository_owner }}
      #    repositories: "release-please-pnpm-mororepo-poc"

      - uses: actions/checkout@v4
      - name: Get current branch
        run: git branch --show-current
        # Show the target branch
      - run: |
          echo "head_ref! ${{ github.head_ref }}"
          echo "base_ref! ${{ github.base_ref }}"
          echo "${VARS_JSON}"
          echo "${GITHUB_JSON}"
          echo "${EVENT_JSON}"
        shell: bash
        env:
          VARS_JSON: ${{ toJSON(vars) }}
          GITHUB_JSON: ${{ toJSON(github) }}
          EVENT_JSON: ${{ toJSON(github.event) }}
        # Show the base branch
      - run: gh pr view ${{ github.event.number }}

      #- uses: codaxio/cdx@v0.14.0
      #  with:
      #    #token: ${{ steps.app-token.outputs.token }}
      #    token: hello
      #    config-file: cli.config.ts